const categories =
[
    {
        id:1,
        title:"Flip-Flops",
        price:800,
        image: "/images/flipflop1.jpg",
        category:"Goa",
        fiber:"",
    },
    {
        id:2,
        title:"Shrug Dress",
        price:1800,
        image: "/images/dress1.jpg",
        category:"Vrindavan",
        fiber:"",
    },
    {
        id:3,
        title:"Saree ",
        price:1200,
        image: "/images/dress7.jpeg",
        category:"Vrindavan",
        fiber:"",
    },
    {
        id:4,
        title:"Women's Shoes",
        price:1000,
        image: "/images/flipflop2.jpg",
        category:"Vrindavan",
        fiber:"",
    },
    {
        id:5,
        title:"Sunscreen Cream",
        price:500,
        image: "/images/product1.jpg",
        category:"Goa",
        fiber:"",
    },
    {
        id:6,
        title:"Bracelet",
        price:200,
        image: "/images/bracelet.jpg",
        category:"Vrindavan",
        fiber:"",
    },
    {
        id:7,
        title:"Waterproof Mobile Cover Bag",
        price:300,
        image: "/images/bag2.jpg",
        category:"dharamshala",
        fiber:"",
    },
    {
        id:8,
        title:"Women's Bag",
        price:1800,
        image: "/images/bag3.jpg",
        category:"Vrindavan",
        fiber:"",
        
    },
    {
        id:9,
        title:"Men's Kurta",
        price:1800,
        image: "/images/dress2.jpeg",
        category:"Vrindavan",
        fiber:"",
    },
    {
        id:10,
        title:"Men's Shirt ",
        price:900,
        image: "/images/dress3.jpg",
        category:"Goa",
        fiber:"Cotton",
    },
    {
        id:11,
        title:"Duppatta ",
        price:1200,
        image: "/images/duppatta.jpg",
        category:"Vrindavan",
        fiber:"Silk",
    },
    {
        id:12,
        title:" Men's T-Shirt",
        price:800,
        image: "/images/dress4.jpg",
        category:"Goa",
        fiber:"Cotton",
    },
    {
        id:13,
        title:"Waist Bag",
        price:1800,
        image: "/images/purse.jpg",
        category:"dharamshala",
        fiber:"Leather",
    },
    {
        id:14,
        title:"Beach Hat",
        price:800,
        image: "/images/hat1.jpg",
        category:"Goa",
        fiber:"Crochet",
    },
    {
        id:15,
        title:"Jhumka's",
        price:800,
        image: "/images/jhumka1.jpg",
        category:"Vrindavan",
        fiber:"Metal",
    },
    {
        id:16,
        title:"Shrug",
        price:800,
        image: "/images/dress6.jpg",
        category:"Goa",
        fiber:"Cotton",
    },
    {
        id:17,
        title:"Crochet Top",
        price:1000,
        image: "/images/dress5.jpg",
        category:"Goa",
        fiber:"Crochet",
    },
    {
        id:18,
        title:"Sharara Kurti",
        price:1800,
        image: "/images/shortkurti.jpg",
        category:"Vrindavan",
        fiber:"",
    },
    {
        id:19,
        title:"JumpSuit",
        price:1800,
        image: "/images/jump.jpg",
        category:"Goa",
        fiber:"",
    },
    {
        id:20,
        title:"Jacket",
        price:1800,
        image: "/images/jack.jpg",
        category:"dharamshala",
        fiber:"Wool",
    },
    {
        id:21,
        title:"Women's Short",
        price:1800,
        image: "/images/short.jpg",
        category:"Goa",
        fiber:"Cotton",
    },
    {
        id:22,
        title:"Women's Trauser",
        price:1000,
        image: "/images/dress10.jpg",
        category:"dharamshala",
        fiber:"Polyster",
    },
    
    {
        id:23,
        title:"Suit",
        price:1800,
        image: "/images/dress8.jpg",
        category:"Vrindavan",
        fiber:"",
    }, 
    {
        id:24,
        title:"Tank T-shirt",
        price:1800,
        image: "/images/dress11.jpg",
        category:"dharamshala",
        fiber:"",
    }, 
    {
        id:25,
        title:"Women's Watch",
        price:1800,
        image: "/images/women_watch.jpg",
        category:"dharamshala",
        fiber:"",
    },{
        id:26,
        title:"Purse",
        price:1800,
        image: "/images/bag1.jpg",
        category:"Goa",
        fiber:"",
    }, {
        id:27,
        title:"Short Frock",
        price:1800,
        image: "/images/dress9.jpg",
        category:"Goa",
        fiber:"Cotton",
    },
    {
        id:28,
        title:"Tracking Bag",
        price:1800,
        image: "/images/tracking1.jpg",
        category:"dharamshala",
        fiber:"Polyster",
    },
    {
        id:29,
        title:"Men's Shoes",
        price:1800,
        image: "/images/mens shoes.jpg",
        category:"dharamshala",
        fiber:"",
    },
    
]
export default categories;